# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 32730fb1d3cfca1f67b6d18244722f5173b94769862fb8335f3be1319a960027984179ea793b053bf2db96ee5d05274295a3d9c1b345d3de14d0a1bb0fc19ac5

test:
  secret_key_base: 4b8907a4fdb5a2bb4907bfe0c85ef47a1b87e6313ad7b124d170bb4a1858c3a951298aef57f57fe867a7110cf9bd82fe7c8e952b63850cc17bbcafd4f85543b5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
